"""Column specifications for every table in the app.

Kept in one place so the tooltips - which are what actually explain each
metric to the person reading the table - stay consistent everywhere.
"""

from __future__ import annotations

from .models import Col

# ---------------------------------------------------------------------------
# Clusters
# ---------------------------------------------------------------------------
CLUSTER_COLUMNS: list[Col] = [
    Col("cluster_id", "#", "int", 44, tip="Cluster id within this run."),
    Col("suspicion_score", "Suspicion", "num", 88, heat=True,
        tip="Composite of edge, agreement, timing, earliness, rarity and size.\n"
            "Damped for small clusters and thin resolved-bet samples."),
    Col("n_members", "Members", "int", 72, heat=True,
        tip="Distinct wallets in the cluster."),
    Col("n_bets", "Bets", "int", 60, tip="Distinct (market, outcome) pairs the cluster holds."),
    Col("n_positions", "Positions", "int", 74, tip="Member-bet pairs, i.e. total bets made in the cluster."),
    Col("n_markets", "Markets", "int", 70),
    Col("n_shared_bets", "Shared", "int", 66, heat=True,
        tip="Bets held by 2+ members on the same side."),
    Col("n_unanimous_bets", "Unanimous", "int", 82, heat=True,
        tip="Bets EVERY member of the cluster participated in."),
    Col("n_core_bets", "Core", "int", 58,
        tip="Bets held by at least the core-membership fraction of the cluster."),
    Col("unanimity_rate", "Unanim %", "pct", 78, heat=True,
        tip="Unanimous bets / shared bets."),
    Col("concordance", "Concord", "pct", 74, heat=True,
        tip="Of markets where 2+ members traded, the share where they all took the same side."),
    Col("total_usd", "Staked", "usd", 88, heat=True, tip="Total USD bought across the cluster."),
    Col("shared_usd", "Shared $", "usd", 86, tip="USD staked on bets held by 2+ members."),
    Col("unanimous_usd", "Unanim $", "usd", 88),
    Col("avg_usd_per_member", "$/Member", "usd", 88, heat=True),
    Col("median_member_usd", "Med member $", "usd", 96),
    Col("max_position_usd", "Max bet", "usd", 84),
    Col("winrate", "Winrate", "pct", 74, heat=True,
        tip="Resolved positions won / resolved positions.\n"
            "Read alongside ROI - buying 95c favourites also wins ~always."),
    Col("winrate_usd", "Winrate $w", "pct", 84, heat=True,
        tip="Win rate weighted by dollars staked."),
    Col("shared_winrate", "Shared WR", "pct", 84, heat=True,
        tip="Win rate restricted to bets 2+ members shared."),
    Col("unanimous_winrate", "Unanim WR", "pct", 88, heat=True,
        tip="Win rate on bets the whole cluster participated in."),
    Col("longshot_winrate", "Longshot WR", "pct", 92, heat=True,
        tip="Win rate on entries below 50c - where private information actually shows."),
    Col("roi", "ROI", "pct", 70, heat=True, tip="P&L / USD staked (all positions, marked to market)."),
    Col("resolved_roi", "ROI (res.)", "pct", 80, heat=True,
        tip="P&L / staked, restricted to resolved markets."),
    Col("shared_roi", "Shared ROI", "pct", 86, heat=True),
    Col("unanimous_roi", "Unanim ROI", "pct", 90, heat=True),
    Col("longshot_roi", "Longshot ROI", "pct", 94, heat=True),
    Col("pnl", "P&L", "usd", 88, heat=True),
    Col("mean_edge_per_share", "Edge/share", "ratio", 88, heat=True,
        tip="Mean (resolution payout − entry price). How far the market was mispriced\n"
            "relative to where they got in."),
    Col("mean_entry_vs_vwap", "Entry vs VWAP", "ratio", 100, heat=True, invert=True,
        tip="Mean entry price minus the market's volume-weighted price.\n"
            "Negative = the cluster consistently got in cheaper than everyone else."),
    Col("median_entry_pct_of_life", "Earliness", "pct", 80, heat=True, invert=True,
        tip="Median position of first entry within the market's traded lifetime.\n"
            "Lower = they arrive early."),
    Col("median_hours_before_close", "Lead time", "hours", 82, heat=True,
        tip="Median hours between first entry and the market's last trade."),
    Col("median_entry_spread_h", "Entry spread", "hours", 90, heat=True, invert=True,
        tip="Median time between the first and last member entering a shared bet.\n"
            "Small = they move together."),
    Col("sync_rate", "Sync rate", "pct", 80, heat=True,
        tip="Share of shared bets where every member entered inside the timing window."),
    Col("mean_price_spread", "Px spread", "ratio", 80, invert=True,
        tip="Mean spread between the best and worst member entry price on a shared bet."),
    Col("mean_rarity_idf", "Rarity", "num", 72, heat=True,
        tip="Mean inverse-document-frequency of the shared bets.\n"
            "High = they agree on obscure markets, not crowd favourites."),
    Col("median_market_volume", "Med mkt vol", "usd", 94, invert=True),
    Col("avg_pairwise_sim", "Avg sim", "ratio", 76, heat=True,
        tip="Mean cosine similarity across internal edges."),
    Col("max_pairwise_sim", "Max sim", "ratio", 76),
    Col("avg_shared_bets", "Avg shared", "num", 84),
    Col("density", "Density", "pct", 72, heat=True,
        tip="Realised internal edges / all possible member pairs."),
    Col("n_edges", "Edges", "int", 62),
    Col("usd_concentration", "Top $ share", "pct", 88, invert=True,
        tip="Largest member's share of cluster stake. High = one whale plus followers."),
    Col("bets_per_member", "Bets/member", "num", 90),
    Col("window_days", "Span (d)", "num", 76),
    Col("first_ts", "First entry", "ts", 122),
    Col("last_ts", "Last entry", "ts", 122),
]

# ---------------------------------------------------------------------------
# Members
# ---------------------------------------------------------------------------
MEMBER_COLUMNS: list[Col] = [
    Col("display", "Trader", "text", 150, tip="Polymarket display name, else pseudonym, else wallet."),
    Col("proxy_wallet", "Wallet", "wallet", 118),
    Col("is_biggest_bettor", "Biggest", "bool", 62,
        tip="Largest total stake in this cluster."),
    Col("is_lead_mover", "Leader", "bool", 62,
        tip="Most often the first member into a shared bet."),
    Col("total_usd", "Staked", "usd", 86, heat=True),
    Col("usd_share_of_cluster", "$ share", "pct", 72, heat=True,
        tip="This wallet's share of the cluster's total stake."),
    Col("n_bets", "Bets", "int", 56),
    Col("n_shared_bets", "Shared", "int", 66,
        tip="Shared bets this wallet participated in."),
    Col("shared_pct", "Shared %", "pct", 76, heat=True,
        tip="Shared bets as a share of this wallet's own bets.\n"
            "High = the wallet is effectively dedicated to the cluster;\n"
            "low = it overlaps while mostly trading its own book."),
    Col("n_markets", "Markets", "int", 68),
    Col("n_trades", "Trades", "int", 64),
    Col("avg_usd", "Avg bet", "usd", 78),
    Col("max_usd", "Max bet", "usd", 78),
    Col("winrate", "Winrate", "pct", 72, heat=True),
    Col("winrate_usd", "Winrate $w", "pct", 82, heat=True),
    Col("roi", "ROI", "pct", 68, heat=True),
    Col("pnl", "P&L", "usd", 84, heat=True),
    Col("first_mover_count", "1st in", "int", 60, heat=True,
        tip="Number of shared bets this wallet entered before every other member."),
    Col("first_mover_rate", "1st in %", "pct", 74, heat=True,
        tip="First-in count / shared bets participated in."),
    Col("avg_entry_rank", "Avg rank", "num", 78, invert=True, heat=True,
        tip="Mean entry order among members on shared bets. 1.0 = always first."),
    Col("avg_lead_time_h", "Lead time", "hours", 82, heat=True, invert=True,
        tip="Mean hours ahead of the cluster's median entry.\nNegative = enters earlier than the pack."),
    Col("median_lead_time_h", "Med lead", "hours", 80, invert=True),
    Col("avg_entry", "Avg entry", "ratio", 78,
        tip="Mean volume-weighted entry price."),
    Col("avg_entry_vs_cluster", "Δ vs cluster", "ratio", 92, heat=True, invert=True,
        tip="Mean entry price minus the cluster's average on the same bet.\n"
            "Negative = this wallet consistently gets the better fill."),
    Col("avg_entry_vs_vwap", "Δ vs market", "ratio", 90, heat=True, invert=True,
        tip="Mean entry price minus the market VWAP - how far off the market they entered."),
    Col("avg_edge_per_share", "Edge/share", "ratio", 86, heat=True),
    Col("median_entry_pct_of_life", "Earliness", "pct", 78, heat=True, invert=True),
    Col("median_hours_before_close", "Before close", "hours", 90),
    Col("avg_sim_to_cluster", "Avg sim", "ratio", 74, heat=True),
    Col("max_sim_to_cluster", "Max sim", "ratio", 74),
    Col("avg_sync_frac", "Sync %", "pct", 70, heat=True,
        tip="Mean share of shared bets entered within the timing window of a peer."),
    Col("degree", "Links", "int", 56, tip="Connections to other cluster members."),
    Col("resolved_bets", "Resolved", "int", 72),
    Col("first_ts", "First seen", "ts", 120),
    Col("last_ts", "Last seen", "ts", 120),
]

# ---------------------------------------------------------------------------
# Bets / positions held by a cluster
# ---------------------------------------------------------------------------
BET_COLUMNS: list[Col] = [
    Col("question", "Market", "text", 320),
    Col("outcome", "Side", "text", 66),
    Col("n_members", "In it", "int", 58, heat=True, tip="Cluster members holding this bet."),
    Col("member_frac", "Coverage", "pct", 76, heat=True,
        tip="Share of the cluster holding this bet."),
    Col("unanimous", "Unanim", "bool", 66, tip="Every member of the cluster is in this bet."),
    Col("core", "Core", "bool", 52),
    Col("total_usd", "Staked", "usd", 88, heat=True),
    Col("avg_entry", "Avg entry", "ratio", 78),
    Col("min_entry", "Best entry", "ratio", 80),
    Col("max_entry", "Worst entry", "ratio", 84),
    Col("price_spread", "Px spread", "ratio", 80, invert=True, heat=True,
        tip="Worst minus best member entry price - how far apart they got in."),
    Col("market_vwap", "Mkt VWAP", "ratio", 80),
    Col("entry_vs_market", "Δ vs market", "ratio", 90, heat=True, invert=True,
        tip="Cluster average entry minus the market's VWAP."),
    Col("first_entrant", "First in", "wallet", 116, tip="Wallet that entered this bet first."),
    Col("first_entry_price", "1st price", "ratio", 78),
    Col("first_entry_ts", "First entry", "ts", 120),
    Col("entry_spread_h", "Entry spread", "hours", 90, heat=True, invert=True,
        tip="Time between the first and last member entering."),
    Col("biggest_bettor", "Biggest in", "wallet", 116),
    Col("biggest_usd", "Biggest $", "usd", 84),
    Col("won", "Won", "bool", 54),
    Col("roi", "ROI", "pct", 70, heat=True),
    Col("pnl", "P&L", "usd", 86, heat=True),
    Col("edge_per_share", "Edge/share", "ratio", 86, heat=True),
    Col("entry_pct_of_life", "Earliness", "pct", 78, heat=True, invert=True),
    Col("hours_before_close", "Before close", "hours", 90),
    Col("rarity_idf", "Rarity", "num", 68, heat=True),
    Col("market_volume", "Mkt volume", "usd", 92),
    Col("market_traders", "Mkt traders", "int", 88),
    Col("sectors", "Sectors", "text", 180),
    Col("event_title", "Event", "text", 200),
    Col("condition_id", "Condition id", "text", 140),
]

# Per-member rows inside one bet (the drill-down under a cluster's position).
POSITION_COLUMNS: list[Col] = [
    Col("proxy_wallet", "Wallet", "wallet", 120),
    Col("display", "Trader", "text", 150,
        tip="Polymarket display name, else pseudonym, else wallet."),
    Col("question", "Market", "text", 300),
    Col("outcome", "Side", "text", 62),
    Col("buy_usd", "Staked", "usd", 86, heat=True),
    Col("buy_shares", "Shares", "num", 88),
    Col("vwap_entry", "Entry", "ratio", 72),
    Col("entry_vs_vwap", "Δ vs market", "ratio", 90, heat=True, invert=True),
    Col("first_buy_ts", "First buy", "ts", 120),
    Col("last_buy_ts", "Last buy", "ts", 120),
    Col("n_trades", "Trades", "int", 62),
    Col("net_shares", "Net", "num", 84),
    Col("sell_usd", "Sold $", "usd", 80),
    Col("won", "Won", "bool", 54),
    Col("pnl", "P&L", "usd", 86, heat=True),
    Col("roi", "ROI", "pct", 70, heat=True),
    Col("edge_per_share", "Edge/share", "ratio", 84, heat=True),
    Col("entry_pct_of_life", "Earliness", "pct", 78, invert=True),
    Col("is_longshot", "Longshot", "bool", 74),
]

MARKET_COLUMNS: list[Col] = [
    Col("question", "Market", "text", 340),
    Col("event_title", "Event", "text", 200),
    Col("sectors", "Sectors", "text", 200),
    Col("volume", "Volume", "usd", 92, heat=True),
    Col("liquidity", "Liquidity", "usd", 88),
    Col("resolved", "Resolved", "bool", 74),
    Col("winning_outcome", "Winner idx", "int", 84),
    Col("start_ts", "Start", "ts", 118),
    Col("end_ts", "End", "ts", 118),
    Col("condition_id", "Condition id", "text", 150),
]

# Metrics offered in the cluster comparison view.
COMPARE_METRICS: list[tuple[str, str, str]] = [
    ("suspicion_score", "Suspicion score", "num"),
    ("n_members", "Members", "int"),
    ("n_bets", "Distinct bets", "int"),
    ("n_positions", "Total bets made", "int"),
    ("n_shared_bets", "Shared bets", "int"),
    ("n_unanimous_bets", "Unanimous bets", "int"),
    ("unanimity_rate", "Unanimity rate", "pct"),
    ("concordance", "Concordance", "pct"),
    ("winrate", "Winrate", "pct"),
    ("shared_winrate", "Shared-bet winrate", "pct"),
    ("unanimous_winrate", "Unanimous winrate", "pct"),
    ("longshot_winrate", "Longshot winrate", "pct"),
    ("roi", "ROI", "pct"),
    ("resolved_roi", "Resolved ROI", "pct"),
    ("shared_roi", "Shared ROI", "pct"),
    ("mean_edge_per_share", "Edge per share", "ratio"),
    ("mean_entry_vs_vwap", "Entry vs market VWAP", "ratio"),
    ("median_entry_pct_of_life", "Earliness", "pct"),
    ("median_entry_spread_h", "Entry spread (h)", "hours"),
    ("sync_rate", "Sync rate", "pct"),
    ("mean_rarity_idf", "Bet rarity", "num"),
    ("avg_pairwise_sim", "Avg similarity", "ratio"),
    ("density", "Graph density", "pct"),
    ("total_usd", "Total staked", "usd"),
    ("avg_usd_per_member", "Stake per member", "usd"),
    ("pnl", "P&L", "usd"),
    ("usd_concentration", "Top-member $ share", "pct"),
]
