"""Create Windows shortcuts for PolyClusters using the app's own icon.

Writes PolyClusters.lnk to three places, each pointing at the project's
pythonw.exe so launching shows no console window:

  <project root>   - launch straight from the source folder
  Desktop
  Start Menu

The icon comes from assets/PolyClusters.ico, generated by build_assets.py from
PolyClusters_logo_icon.png; it is built here automatically if missing.

Run:  .venv/Scripts/python.exe scripts/make_shortcut.py
      .venv/Scripts/python.exe scripts/make_shortcut.py --project-only
      .venv/Scripts/python.exe scripts/make_shortcut.py --desktop-only
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
for stream in (sys.stdout, sys.stderr):
    try:
        stream.reconfigure(encoding="utf-8", errors="replace")
    except AttributeError:
        pass

from polyclusters.config import APP_ICO, APP_NAME, WINDOWS_APP_ID  # noqa: E402

# PowerShell does the COM work; it avoids a pywin32 dependency just for this.
PS_TEMPLATE = r"""
$ws = New-Object -ComObject WScript.Shell
$sc = $ws.CreateShortcut('{lnk}')
$sc.TargetPath       = '{target}'
$sc.Arguments        = '{args}'
$sc.WorkingDirectory = '{workdir}'
$sc.IconLocation     = '{icon}'
$sc.Description      = '{description}'
$sc.WindowStyle      = 1
$sc.Save()
"""


def _pythonw() -> Path:
    """Prefer the venv's windowless interpreter so no console flashes up."""
    for candidate in (
        ROOT / ".venv" / "Scripts" / "pythonw.exe",
        Path(sys.executable).with_name("pythonw.exe"),
        Path(sys.executable),
    ):
        if candidate.exists():
            return candidate
    return Path(sys.executable)


def ensure_ico() -> bool:
    """Build the .ico from the source PNG if it is not there yet."""
    if APP_ICO.exists():
        return True
    print("PolyClusters.ico missing — building it from the source PNG...")
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "build_assets.py")],
        capture_output=True, text=True,
    )
    print("  " + (result.stdout or result.stderr).strip().replace("\n", "\n  "))
    return APP_ICO.exists()


def make_shortcut(lnk: Path) -> bool:
    target = _pythonw()
    icon = APP_ICO

    script = PS_TEMPLATE.format(
        lnk=str(lnk).replace("'", "''"),
        target=str(target).replace("'", "''"),
        args="-m polyclusters",
        workdir=str(ROOT).replace("'", "''"),
        icon=f"{icon},0".replace("'", "''"),
        description=f"{APP_NAME} — Polymarket co-betting cluster analysis",
    )
    lnk.parent.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        ["powershell", "-NoProfile", "-NonInteractive", "-Command", script],
        capture_output=True, text=True,
    )
    if result.returncode != 0 or not lnk.exists():
        print(f"  ! failed: {(result.stderr or result.stdout).strip()[:200]}")
        return False
    print(f"  created {lnk}")
    return True


def main() -> int:
    if os.name != "nt":
        print("Shortcuts are Windows-only. On macOS/Linux use ./run.sh.")
        return 1
    if not ensure_ico():
        print("Could not produce PolyClusters.ico; aborting.")
        return 1

    print(f"Target        : {_pythonw()} -m polyclusters")
    print(f"Working dir   : {ROOT}")
    print(f"Icon          : {APP_ICO}")
    print(f"AppUserModelID: {WINDOWS_APP_ID}\n")

    project_lnk = ROOT / f"{APP_NAME}.lnk"
    if "--desktop-only" in sys.argv:
        targets = [Path(os.path.expanduser("~/Desktop")) / f"{APP_NAME}.lnk"]
    elif "--project-only" in sys.argv:
        targets = [project_lnk]
    else:
        targets = [project_lnk, Path(os.path.expanduser("~/Desktop")) / f"{APP_NAME}.lnk"]
        appdata = os.environ.get("APPDATA")
        if appdata:
            targets.append(
                Path(appdata) / "Microsoft" / "Windows" / "Start Menu" / "Programs"
                / f"{APP_NAME}.lnk"
            )

    ok = all([make_shortcut(t) for t in targets])
    if ok:
        print(
            "\nDone. The icon may take a moment to refresh in Explorer; if the old "
            "one lingers, press F5 on the Desktop."
        )
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
